import type { Metadata } from "next";
import { BellRing, Building2, Database, KeyRound, Save, ShieldCheck, UsersRound } from "lucide-react";

export const metadata: Metadata = { title: "Settings" };

export default function SettingsPage() {
  return (
    <div className="page-stack settings-page">
      <div className="page-header"><div><p className="page-kicker">WORKSPACE</p><h1>Settings</h1><p>Manage your organization, team and platform preferences.</p></div><button className="primary-button" type="button"><Save size={16} /> Save changes</button></div>
      <div className="settings-layout"><nav className="settings-nav"><a className="active" href="#organization"><Building2 /> Organization</a><a href="#team"><UsersRound /> Team & roles</a><a href="#security"><ShieldCheck /> Security</a><a href="#notifications"><BellRing /> Notifications</a><a href="#integrations"><Database /> Integrations</a><a href="#api"><KeyRound /> API access</a></nav><section className="settings-content"><article className="panel" id="organization"><div className="settings-section-head"><div><p className="panel-eyebrow">ORGANIZATION</p><h2>Workspace details</h2><p>These details appear across reports and customer communications.</p></div><span className="settings-logo">AG</span></div><div className="form-grid"><label><span>Workspace name</span><input defaultValue="AfriGate Demo" /></label><label><span>Workspace URL</span><div className="input-prefix"><i>app.afrigate.ai/</i><input defaultValue="afrigate-demo" /></div></label><label><span>Primary market</span><select defaultValue="kenya"><option value="kenya">Kenya</option><option value="nigeria">Nigeria</option><option value="south-africa">South Africa</option></select></label><label><span>Reporting currency</span><select defaultValue="usd"><option value="usd">USD — US Dollar</option><option value="kes">KES — Kenyan Shilling</option></select></label><label className="full"><span>Business address</span><input defaultValue="Westlands Business Park, Nairobi, Kenya" /></label></div></article><article className="panel" id="security"><div className="settings-section-head"><div><p className="panel-eyebrow">DATA & SECURITY</p><h2>Platform controls</h2><p>Enterprise-grade protection is enabled for this workspace.</p></div></div><div className="setting-toggles"><div><span><strong>Multi-factor authentication</strong><small>Require MFA for workspace administrators.</small></span><button className="toggle on" type="button"><i /></button></div><div><span><strong>AI recommendation history</strong><small>Retain an auditable record of AI signals and actions.</small></span><button className="toggle on" type="button"><i /></button></div><div><span><strong>Weekly operations digest</strong><small>Email a performance summary every Monday.</small></span><button className="toggle" type="button"><i /></button></div></div></article></section></div>
    </div>
  );
}
